services:
  db: 
    image: postgres 
    restart: always 
    environment: 
      POSTGRES_USER: giga 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight_api 
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432 

  pgadmin:
    image: dpage/pgadmin4:8.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gigakatamadze0@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: <your_strong_password>
    ports:
      - "5050:80" 