services:
  db:
    image: postgres:16.4 
    restart: always    
    environment:
      POSTGRES_USER: giga
      POSTGRES_DATABASE: greenlight_api 
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports: 
      - 54320:5432    